#!/bin/bash
# MemoryTutor Interactive Setup Script
# This script guides you through setting up MemoryTutor step-by-step

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo "=============================================="
echo "  🌍 MemoryTutor Interactive Setup"
echo "=============================================="
echo ""
echo "This script will help you set up MemoryTutor in just a few minutes."
echo ""

# Check Python version
echo -e "${BLUE}Step 1: Checking Python installation...${NC}"
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}✗ Python 3 is not installed.${NC}"
    echo "Please install Python 3.11 or higher from: https://www.python.org/downloads/"
    exit 1
fi

python_version=$(python3 --version 2>&1 | grep -Po '(?<=Python )\d+\.\d+')
required_version="3.11"

if [ "$(printf '%s\n' "$required_version" "$python_version" | sort -V | head -n1)" != "$required_version" ]; then
    echo -e "${RED}✗ Python $required_version or higher required.${NC}"
    echo "Found: Python $python_version"
    echo "Please upgrade Python."
    exit 1
fi

echo -e "${GREEN}✓ Python $python_version detected${NC}"
echo ""

# Create virtual environment
echo -e "${BLUE}Step 2: Setting up virtual environment...${NC}"
if [ -d "venv" ]; then
    echo -e "${YELLOW}⚠ Virtual environment already exists.${NC}"
else
    python3 -m venv venv
    echo -e "${GREEN}✓ Virtual environment created${NC}"
fi

# Activate virtual environment
source venv/bin/activate

# Install dependencies
echo ""
echo -e "${BLUE}Step 3: Installing dependencies...${NC}"
pip install --upgrade pip -q
pip install -r requirements.txt -q
echo -e "${GREEN}✓ Dependencies installed${NC}"

# Configure environment
echo ""
echo -e "${BLUE}Step 4: Configuring MemoryTutor...${NC}"
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠ Configuration file (.env) already exists.${NC}"
    read -p "Do you want to reconfigure? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        echo ""
        echo -e "${GREEN}Setup complete! Run: python tutor.py${NC}"
        exit 0
    fi
fi

# Collect configuration
echo "Let's configure your tutor. Press Enter to use defaults shown in [brackets]."
echo ""

# OpenAI API Key
echo -e "${YELLOW}Required: OpenAI API Key${NC}"
echo "Get your API key from: https://platform.openai.com/api-keys"
read -p "Enter your OpenAI API key: " openai_key
while [ -z "$openai_key" ]; do
    echo -e "${RED}OpenAI API key is required!${NC}"
    read -p "Enter your OpenAI API key: " openai_key
done
echo ""

# Language selection
echo -e "${YELLOW}Language Selection${NC}"
echo "Which language would you like to learn?"
echo "Examples: Spanish, French, German, Italian, Japanese, Chinese, Portuguese"
read -p "Language [Spanish]: " language
language=${language:-Spanish}
echo ""

# User ID
echo -e "${YELLOW}User ID${NC}"
echo "A unique identifier for tracking your progress."
read -p "User ID [default_student]: " user_id
user_id=${user_id:-default_student}
echo ""

# Memory mode
echo -e "${YELLOW}Memory Storage Mode${NC}"
echo "1) Self-hosted (local, free, private) - Recommended for most users"
echo "2) Hosted (Mem0 cloud, requires API key)"
read -p "Choose mode [1]: " mode_choice
mode_choice=${mode_choice:-1}

if [ "$mode_choice" == "2" ]; then
    mem0_mode="hosted"
    echo ""
    echo "Get your Mem0 API key from: https://mem0.dev/keys-beau"
    echo "Sign up at: https://mem0.dev/beau-yt"
    read -p "Enter your Mem0 API key: " mem0_key
    while [ -z "$mem0_key" ]; do
        echo -e "${RED}Mem0 API key is required for hosted mode!${NC}"
        read -p "Enter your Mem0 API key (or press Ctrl+C to cancel): " mem0_key
    done
else
    mem0_mode="self-hosted"
    mem0_key=""
fi
echo ""

# Create .env file
echo -e "${BLUE}Creating configuration file...${NC}"
cat > .env << EOF
# ============================================
# MemoryTutor Configuration
# Generated by interactive setup
# ============================================

# OpenAI Configuration (REQUIRED)
OPENAI_API_KEY=$openai_key

# Application Configuration
TUTOR_LANGUAGE=$language
USER_ID=$user_id

# Memory Mode
MEM0_MODE=$mem0_mode
EOF

if [ "$mem0_mode" == "hosted" ]; then
    cat >> .env << EOF
MEM0_API_KEY=$mem0_key
EOF
else
    cat >> .env << EOF

# Self-Hosted Configuration
USE_DOCKER_QDRANT=false
QDRANT_PATH=.qdrant_data
QDRANT_COLLECTION_NAME=language_tutor_session
EOF
fi

echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""

# Summary
echo "=============================================="
echo "  🎉 Setup Complete!"
echo "=============================================="
echo ""
echo "Your configuration:"
echo "  Language:    $language"
echo "  User ID:     $user_id"
echo "  Memory:      $mem0_mode"
echo ""
echo "To start learning, run:"
echo -e "  ${GREEN}source venv/bin/activate${NC}"
echo -e "  ${GREEN}python tutor.py${NC}"
echo ""
echo "Or simply run:"
echo -e "  ${GREEN}./scripts/run.sh${NC}"
echo ""
echo "Commands you can use in the tutor:"
echo "  /memories     - View what the tutor knows about you"
echo "  /forget [num] - Delete a specific memory"
echo "  /help         - Show all commands"
echo "  exit          - Exit the tutor"
echo ""
echo "Happy learning! 🚀"
echo ""
